[build]
  command = "expo build:web"
  publish = "web-build"

[context.production.environment]
  NODE_VERSION = "20.17.0"
  API_URL = "https://your-api-url.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
